### ISSUE TITLE
Peer to peer code review in the Morning Session

### ISSUE THREAD

**Issue by Ruthmy** [MyMicroverseProjects/PortfolioProject#15]
Hey there!  How's it going Alejandro? 👋 
We saw your project today at the peer to peer code review, and we have some ideas for you to improve it.

**Ruth:**

-  ✔️ Your project has evolved very well, I am impressed by the progress you have made so far.
 Remember to update your README.md file with any new changes you've made, and add your future updates, like the local storage for the form.
- 💡 This is just an idea, but maybe you can use the property `scale: 0.9;` to help you change the size of the rendering modal without affect the user experience.

**Fredo:**

- Good implementation 👍 
Good work with the design 💯 
Kindly remove the repeat functionality in the description of project because this is a duplication , you can add all your description into the `object.modal ` [&#128521;].
**Optional** 
Your can use` elementOnTop.scrollIntoView();` for scrolling automatically to top  [&#128521;].

**Eric:**

- Great work Salazar 🙂 however, I have an optional suggestion; when I click on the 'see project' button in the desktop version, I can't see the whole card in the popup window. Please try to solve that issue, maybe the property `overflow: scroll;` help you at this point to allow see a scroll bar on the modal window.

 
It's nice to see how your skills have improved and how you are progressing in your work, well done. 💯 
Thank you very much for sharing your work with us 🤝

**Comment by xandro2021** [comment]
I fixed it by making the modal scrollable and the body unable to scroll. Still love the recommendations, they all are interesting and useful.
