### ISSUE TITLE
Img file and tag name in css

### ISSUE THREAD

**Issue by federicaulzurrun** [MyMicroverseProjects/PortfolioProject#9]
Hi!
-I suggest you delete all the images that you are not using on your page because it makes the page heavier and it's not good for SEO.
- Other suggestion is to try not to use in css the name of the html tag, it is better if you assign a class to the html tag so you can use it later on css.

**Comment by xandro2021** [comment]
@federicaulzurrun  the revenge, the revenge jaja 😄 
Jajaja just kidding. Yeap, I have to clean that. I was experimenting with all those images and then I didn't know which was to delete.
Thank you for your advice :)

**Comment by xandro2021** [comment]
Also, I need to create a media query for resolutions higher than 720p. My CSS styles just brake after width of 1550px
